micronaut:
    application:
        name: redblue
mongodb:
    uri: mongodb://${ME_CONFIG_MONGODB_ADMINUSERNAME:admin}:${ME_CONFIG_MONGODB_ADMINPASSWORD:pass}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}